FROM golang:1.25.0 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/diasoft-gateway-consumer ./cmd/diasoft-gateway-consumer

FROM gcr.io/distroless/base-debian12
COPY --from=build /bin/diasoft-gateway-consumer /diasoft-gateway-consumer
ENTRYPOINT ["/diasoft-gateway-consumer"]
