FROM golang:1.25.0 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/diasoft-gateway-dlq-replayer ./cmd/diasoft-gateway-dlq-replayer

FROM gcr.io/distroless/base-debian12
COPY --from=build /bin/diasoft-gateway-dlq-replayer /diasoft-gateway-dlq-replayer
ENTRYPOINT ["/diasoft-gateway-dlq-replayer"]
